import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import navTop from './(component)/nav';
 
import 'bootstrap-icons/font/bootstrap-icons.css'
import BankLoader from './loading';
// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default    function RootLayout({ children }) {

  return (
    <ClerkProvider>
      <html lang="en">
        
        <body className={` antialiased`}>
          {/* <BankLoader/> */}
          {children}
        </body> 
      </html>
    </ClerkProvider>
  )
}
